enum AmityPermission {
  BAN_USER,
  EDIT_USER,
  CREATE_ROLE,
  DELETE_ROLE,
  EDIT_USER_FEED_POST,
  DELETE_USER_FEED_POST,
  EDIT_USER_FEED_COMMENT,
  DELETE_USER_FEED_COMMENT,
  ADD_COMMUNITY_USER,
  REMOVE_COMMUNITY_USER,
  EDIT_COMMUNITY_USER,
  BAN_COMMUNITY_USER,
  MUTE_COMMUNITY_USER,
  EDIT_COMMUNITY,
  EDIT_COMMUNITY_POST,
  DELETE_COMMUNITY_POST,
  PIN_COMMUNITY_POST,
  EDIT_COMMUNITY_COMMENT,
  DELETE_COMMUNITY_COMMENT,
  REVIEW_COMMUNITY_POST,
}

extension AmityPermissionExtension on AmityPermission {
  String get value {
    return [
      'BAN_USER',
      'EDIT_USER',
      'CREATE_ROLE',
      'DELETE_ROLE',
      'EDIT_USER_FEED_POST',
      'DELETE_USER_FEED_POST',
      'EDIT_USER_FEED_COMMENT',
      'DELETE_USER_FEED_COMMENT',
      'ADD_COMMUNITY_USER',
      'REMOVE_COMMUNITY_USER',
      'EDIT_COMMUNITY_USER',
      'BAN_COMMUNITY_USER',
      'MUTE_COMMUNITY_USER',
      'EDIT_COMMUNITY',
      'EDIT_COMMUNITY_POST',
      'DELETE_COMMUNITY_POST',
      'PIN_COMMUNITY_POST',
      'EDIT_COMMUNITY_COMMENT',
      'DELETE_COMMUNITY_COMMENT',
      'REVIEW_COMMUNITY_POST',
    ][index];
  }
}
